### ISSUE TITLE
Editing Item

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#111] opened 2018-07-04 09:19 UTC
@fabian 
Hi, 
We've just noticed a new bug when we try to edit an item from the "skills view". 
As shown in the screenshot below, we get an error message when trying to save modification on the item in section "installation". 
![editing item](https://user-images.githubusercontent.com/39295271/42268196-32879af8-7f7b-11e8-8d2b-9c44a6228437.png)

A big issue for us since we are working at the moment on collecting all the electricals needs and have to implement that into the IL. 

Thanks in advance

**Comment by fabian** [comment] 2018-07-13 07:48
@ailtisWSFR The problem is caused by the Ampere value "5.7" - unfortunately IL can only save full numbers for Ampere at the moment.

**Comment by ailtisWSFR** [comment] 2018-07-18 14:55
@fabian Ok thanks, we will only work with full numbers then. You say "at the moment", does it mean that in the future it's going to be possible to have comma numbers?

**Comment by fabian** [comment] 2018-07-23 15:41
Feel free to create a new issue with the request to add the support for comma numbers in Ampere, I will close this "bug" for now.

**Closed by fabian** 2018-07-23 15:41 UTC
Labels: Bug, Critical Priority
