### ISSUE TITLE
Recommend changes to supplied items

### ISSUE THREAD

**Issue by Joni-Aaltonen** [worldskills/worldskills-infrastructure-list#85] opened 2018-05-17 10:10 UTC
Here are some things to consider when adding a functionality to recommend suggestions to supplied items

- In WSI competitions this is not really needed, as when the details are shown to the public, the contracts are already signed in most cases, and changes are not possible. This means that the feature should be configurable per-event

- There should be a warning shown during the approval process if the supplied item has been linked to multiple skills, and the confirmation window should show a list of requested items where the item is linked, similarly how catalogue view already has functionality "show-linked" (see screencap below)
![image](https://user-images.githubusercontent.com/428709/40171292-7d1b2044-59d3-11e8-9934-78643ffc2b0f.png)

- Approvals should only be possible by the organizer in case the item is linked to multiply skills. I'm not sure if this is always the case already, but it can be dangerous if the expert/WSM can make this approval that affects multiple skills.

**Comment by Joni-Aaltonen** [comment] 2018-06-01 09:51
@ailtisWSFR I'm working on this feature now, do you think it would be enough to allow recommending changes to only the fields which are in the "general" tab of the supplied item.

In my opinion there would be no need to allow recommending changes to the details they don't actually see on the public view.

This would mean allowing recommendations to:
- Manufacturer 
- Model 
- Size
- Part number 
- Subcategory
- Priority

This also would make the change much cleaner from code maintenance point of view.

**Comment by Joni-Aaltonen** [comment] 2018-06-01 09:52
I'm also making this configurable by adding a new Role in auth called `RecommendSupplied` - in case no one in the event has this role, this tab will remain hidden. It's an easy way to either allow/disallow this per-event.

**Comment by ailtisWSFR** [comment] 2018-06-01 10:38
@Joni-Aaltonen It would be good for us to also allow recommendation for the fields "Installation" and "Extra". The must would also to give them the possibility to recommend adding "Files".
(We wish to have those possibilities since it's our Experts who often provide the information present in those fields)

Other question: during the approval process, will it offer the possibility to "Split Supplied Item" before approving the recommendation? It will prevent the changes of items linked to multiple skills.

**Comment by Joni-Aaltonen** [comment] 2018-06-01 10:53
@ailtisWSFR  
Ok, I'll proceed with adding the full information 👍 

As for the "split supplied item" option, I have yet to look at the interface for that section. But I'll definitely investigate that option when I do. 

Anything else I need to take into consideration when implementing this feature?

**Comment by ailtisWSFR** [comment] 2018-06-01 11:09
@Joni-Aaltonen 
Not that I'm aware no. Thanks.

**Comment by Joni-Aaltonen** [comment] 2018-06-11 08:54
Small status update, work is progressing on recommendations for supplied items, the user interface for adding requests already works, including file uploads. Starting to work on the approval view now, will be posting UI mockups once I get the UI sorted out

![image](https://user-images.githubusercontent.com/428709/41221850-0ae92e4a-6d6e-11e8-8500-89ce33e86132.png)

**Comment by Joni-Aaltonen** [comment] 2018-06-12 08:46
Hi @ailtisWSFR @fabian 

I've created a few rough mockups on the UI for reviewing these modifications with supplied information. I'll cleanup the user interface to make it look a bit better during implementation if the suggested workflow works for you.

I've basically replaced the current approval view with a new interface for reviewing, editing and accepting/denying the recommendations.

The recommendation will still happen from the public view as per the screenshot above.

This is what the current recommendations landing view looks like
![image](https://user-images.githubusercontent.com/428709/41279639-b90665d4-6e35-11e8-9227-e0aff11a9af7.png)

The blue button on the right side of each item opens up a review window with the proposed changes, if the item only has changes to the requested item details, it will only show those details. *BUT* if there are also changes to the supplied item details (separate permission layer), the form will also show and highlight any changes made to the supplied item. Any changes are highlighted with the warning (orange) background color, in the example only one row is highlighted.

You'll also have the ability to mark the item to be cloned/splitted, instead of modifying the actual supplied item. I'll also add in a button to show where the item is being used already, as well as a warning in case the item is used in any other skills.

![image](https://user-images.githubusercontent.com/428709/41279727-ee33788c-6e35-11e8-9884-a2e534013aca.png)

Before accepting the recommendation, I've also added a possibility to edit the full recommendation, allowing you to make quick changes before approval, see screenshot below

![image](https://user-images.githubusercontent.com/428709/41279849-38f283b8-6e36-11e8-8593-6d2279c8eff4.png)

Please let me know if this workflow works for you, and I'll continue on implementing the features and tidying up the user interface.

**Comment by Joni-Aaltonen** [comment] 2018-06-12 08:47
Note that the screenshot above does not yet have all the fields that are available for the supplied item.

Also I'm planning on hiding any fields from the view that are empty, just to make review easier.

**Comment by ailtisWSFR** [comment] 2018-06-12 13:27
Hi @Joni-Aaltonen 
The suggested workflow does work for me. 
Juste a question about clone/split item: will the button appear only if the item is actually used in another skill (with the warning)?  I think this would be better becose if the item is only used in that skill, there is no reason to create a new copy of the supplied item. 
That's my point of view but if you prefer making it available all the time  (and easier to code ? ), that's fine with me too.

**Comment by Joni-Aaltonen** [comment] 2018-06-14 05:32
Hi @ailtisWSFR and thanks for commenting, I can hide it in case the item is not used in any other skills.
I'll continue with implementation and will let you know if I run into anything that requires more feedback.

**Comment by ailtisWSFR** [comment] 2018-07-23 16:05
@Joni-Aaltonen @fabian 
Hi! Is it possible to have an idea of when this new feature will be released? 
It would be a big help in the daily use of the IL for our Experts and Workshop managers. Can I help in some ways to make it released faster? 
Thanks in advance.

**Comment by fabian** [comment] 2018-07-23 16:07
@ailtisWSFR Sorry I was away for meetings last week, I will try to have a look at the changes made by Joni again this week. Hopefully we can then have this released next week.

**Comment by fabian** [comment] 2018-07-24 15:55
@ailtisWSFR @Joni-Aaltonen The new functionality is now available on staging for testing: https://staging-il.worldskills.org/

**Comment by fabian** [comment] 2018-07-26 11:39
@ailtisWSFR  Which group of people should I give the permissions for recommending supplied item changes?

**Comment by ailtisWSFR** [comment] 2018-07-26 13:02
@fabian The same people who have access to the recommendation at the moment will have access to the supplied item recommendations. ( Experts and Workshop Manager + IL admin)

Also, I've tried the recommending tool on staging and I've noticed two things: 
 - First: there is a bug and as soon as I click on the button to make a recommendation, I get the two error messages (see screenshot below) and it goes back to the Skills View. 
![image](https://user-images.githubusercontent.com/39295271/43263529-cdb5bd56-90e3-11e8-8f13-e631b63bbc04.png)
Therefore I'm not able to test the new recomendation system. 

- Second: we need to keep the possibility to make a recommendation for the 3 status: "Requested", "Prospect" and "Pending". 
Only the status "Confirmed" should not allow recommendations. 
(At the moment, only lines with the status "Requested" alow recommendations on the staging IL)
Is it possible to make this change for the French event? 

Thanks

**Comment by fabian** [comment] 2018-07-26 13:08
@ailtisWSFR Okay, I've adjusted the permissions, can you try again?

@Joni-Aaltonen Can you adjust it so the "Recommend" button always shows when there the status has the flag `allow_editing`?

**Comment by ailtisWSFR** [comment] 2018-07-26 13:17
@fabian Ok, now I only get one error message : 
![image](https://user-images.githubusercontent.com/39295271/43264366-393847ea-90e6-11e8-869f-f11258432dff.png)

Also I noticed that informations of the "Requested item "are empty in the window  (not showing the "Description", "Quantity", "Potential supplier" ....) We should have the information that are already saved in the systeme like in the previous "Recommend a modification" system.

**Comment by ailtisWSFR** [comment] 2018-07-26 13:30
@fabian @Joni-Aaltonen Another bug, on the recommendations landing view, the little exclamation point did appear on a recommendation when I've clicked on the "i" button, but the recommendation does not include supplied item changes. 
 
![image](https://user-images.githubusercontent.com/39295271/43265256-877662a0-90e8-11e8-8212-35f6bd6708ec.png)
![image](https://user-images.githubusercontent.com/39295271/43265319-b06aa2de-90e8-11e8-9111-6d4dce5c64ad.png)

**Comment by fabian** [comment] 2018-07-30 08:31
@Joni-Aaltonen Can you check the bugs reported by Arthur?

**Comment by Joni-Aaltonen** [comment] 2018-07-30 12:22
@fabian sure I'll be working tonight and will take a look

**Comment by Joni-Aaltonen** [comment] 2018-07-30 22:40
@fabian re: ```Can you adjust it so the "Recommend" button always shows when there the status has the flag allow_editing?```

The prospect isn't showing editing options as it's marked as a `secret` status. By design it does not make sense to allow suggesting changes to an item that is not made public. This is a required feature in WSI competitions. In WSFR this would be made possible if the `secret` tag on `prospect` status would be set to `0`.

If the item details need to be kept secret, the `show_details_in_public_view` can be set to `0`.

Will get back to the bug soon.

**Comment by Joni-Aaltonen** [comment] 2018-07-30 22:43
@ailtisWSFR The reason why the details of the "secret" / `prospect` item are left blank is that the print view by design makes it impossible for the user to fetch those details in this view. Secret items are meant to be kept unknown to anyone who uses the "public view".

In your case as mentioned above, we can switch the `prospect` status to be a "non-secret" status, which would solve your problem.

**Comment by Joni-Aaltonen** [comment] 2018-07-30 22:54
@ailtisWSFR Supplied item details not getting saved was a bug, sorry about that. I've pushed a fix for @fabian to review and deploy. The supplied item details recommended before this patch being deployed unfortunately were not saved, and thus cannot be shown, but the form functions correctly now.

**Comment by fabian** [comment] 2018-07-31 07:50
@ailtisWSFR I've update the status "Prospect" now to not be secret. Editing is now available for it too.

**Comment by ailtisWSFR** [comment] 2018-08-06 10:55
@fabian @Joni-Aaltonen See below the video of the bugs : 

https://www.dropbox.com/s/qis34smom3e4pv3/BUG%20issue%2085.avi?dl=0 

1 - An error message appears when clicking on the orange "recommend changes" button saying: "Could not get supplied item: No access to view secret items"
2 - Information already saved about the "requested item" (like "Description", Quantity" or "Potential supplier") not present in the field on the pop-up window to recommend changes
3 - Information already saved about the "Supplied items" (like "Model" or "Part number") not present in the field on the pop-up window to recommend changes

The two last bug (**2 & 3** ) need at least to be fixed before deployment in production IL or it will generate a loss of information when people we do recommendations. 
Thanks

**Comment by fabian** [comment] 2018-08-06 11:01
@ailtisWSFR Okay, will look into this issues before doing a deployment.

**Comment by ailtisWSFR** [comment] 2018-08-06 14:37
@fabian It does work now on staging! Thanks. 
Two little things remain : 
 - In the "Recommendations" tool, when I click on "Modify Recommendation before accepting", I get the "Original" information filed in the window instead of the "Recommended" information. 
 - The "Date and time" is weird (maybe because of the "^" in "août"?) 
![image](https://user-images.githubusercontent.com/39295271/43722849-8abdedd2-9996-11e8-88f1-3c40ba670284.png)

Out of that, it seems to works just fine !

**Comment by fabian** [comment] 2018-08-06 14:55
@ailtisWSFR Okay, thanks! I will try to have a look at those small issues, currently planning to deploy to production tomorrow.

**Comment by fabian** [comment] 2018-08-07 10:48
@ailtisWSFR I think I was able to fix both problems on staging now, can you do a quick check again?

**Comment by ailtisWSFR** [comment] 2018-08-08 13:16
@fabian Thanks, both bugs have been fixed!

Regarding dropping files in "Files and Pictures", the suggestion does work and the files charged when you click on "Save item" at the end.

The only things are that : 
-  you don't see files already put in when you "Recommend a modification"
 - In "Recommendations" tool, when you click on the files, the redirection doesn't work and you get a "404 Not Found" when trying to see what file it is. 
Also, the "Modify Recommendation before accepting" doesn't show the file.
And finally, when you accept the modification, you get both files for the item (which is good, it mean that you don't lose information...) 

Those issues are minors and we can totally work with this new tool without fixing them. 

@fabian @Joni-Aaltonen Thanks again for your work and this new feature that will be very helpful.
Okay for deploying it on production. 

Cheers

**Comment by fabian** [comment] 2018-08-08 13:25
@ailtisWSFR Perfect, thanks! I have copied those issues into https://github.com/worldskills/worldskills-infrastructure-list/issues/118.

Will deploy this afternoon and close this issue once done!

**Comment by fabian** [comment] 2018-08-08 13:44
Deployed.

**Closed by fabian** 2018-08-08 13:44 UTC
Labels: Enhancement, Mockups needed
