### ISSUE TITLE
Tools: Requested items / Recherche et extraction d'items

### ISSUE THREAD

**Issue by Simon-Woirgard** [worldskills/worldskills-infrastructure-list#70] opened 2018-04-30 07:44 UTC
Hi @PierreAnctil, @azanetti,

I noticed several bug with the item requeste tool.
I do not understand because they are bugs that we normally correct following their recovery on your test platform.

Example of this morning:
1- I go to the Requested items tool
2- I make several filters (Skill sector & subcategory)
3- I select the boxes
4- I click on Edit selected
5- I modify two elements (Status & Potential supplier)
Result:
The statuses of the lines concern this change well (and not all) and potential supplier does not change as asked.

Could you fixe that bug as soon as you can, and look generally if there are no other bug in this tool.

Thanking you in advance

**Comment by PierreAnctil** [comment] 2018-04-30 11:49
@WorldSkillsFrance I reproduced all your steps in staging and couldn't find a bug:

![2018-04-30_13-46-04](https://user-images.githubusercontent.com/6544411/39425714-f139e5c8-4c7c-11e8-938e-c74724da573e.gif)

When I go to see the requested item in the skill view, everything seems OK as well.

Could you please provide us with details on how to reproduce the bug?

**Comment by WorldSkillsFrance** [comment] 2018-04-30 11:53
@PierreAnctil did you do that test in production ? because when i do that in production it does not work

**Comment by PierreAnctil** [comment] 2018-04-30 13:04
@WorldSkillsFrance That was in staging. I tried the same thing in production and that also worked.

**Comment by WorldSkillsFrance** [comment] 2018-04-30 13:07
I just try and it seems that work some time. But not all the time as you can see below
![image](https://user-images.githubusercontent.com/33081412/39428594-427a80b8-4c88-11e8-964d-abbb99e39701.png)

**Comment by WorldSkillsFrance** [comment] 2018-04-30 14:05
I have the problem when there is different statut and i want to put the same statut and name of the potential supplier.

This bug just appear now:
1- i select line with same statut and potential supplier
2- i try to change the statut, and ecrase the name who was written by an other one.
Result : 
Statut well change and nothing appear on the potential supplier
![image](https://user-images.githubusercontent.com/33081412/39431223-5a05228a-4c90-11e8-968d-49875d6f5f70.png)

**Comment by WorldSkillsFrance** [comment] 2018-04-30 14:14
Other Bug : 
Before i search all item with Point P written in (potential supplier) and not all was show. 
When i do a focus on one skills (carrelage/wall for tilling) i saw some point item i try to modify all (statut and the name of the potential supplier and we get this : 
![image](https://user-images.githubusercontent.com/33081412/39431553-6838f344-4c91-11e8-80c6-ec9361a66519.png)
![image](https://user-images.githubusercontent.com/33081412/39431569-755f95aa-4c91-11e8-9383-dd99d0350eb8.png)

Some statut are change but not all
Some potential supplier are change but not all 
....

**Comment by PierreAnctil** [comment] 2018-04-30 14:26
@WorldSkillsFrance we have reproduced this problem and are working on it

**Comment by WorldSkillsFrance** [comment] 2018-04-30 15:09
ok thx
I think that I am in front of another bug and if this one and truthful it is a very big problem.
I can not be sure because I only see it now and this is the result of work between Saturday and today.

Saturday I started to work on skills and one in particular, put the right things in the right fields and add the "potential supplier".
Today I return to a job in which I worked a lot on Saturday and in potential supplier I see POINT P.
I do not see why I would put this in the field potential supplier. There is really no reason.

I am very afraid that when making multiple changes it does not change the good line.
### **Could you check that when changing several items it does not change the status or potential supplier of another line?**

**Comment by PierreAnctil** [comment] 2018-05-02 07:01
@WorldSkillsFrance I ran some tests and could not reproduce the issue. I also checked the code and it seems reliable. Are you sure that was not a misclick?

**Comment by WorldSkillsFrance** [comment] 2018-05-02 07:58
well can not be sure that there is no miss clic, but it's happen to much time on to much scenarios for a misclick, so yes there is something.

Again, find a new bug appear sometime : Bug when we search item. you can see on the screen shot below : 
![image](https://user-images.githubusercontent.com/33081412/39511890-4a324940-4def-11e8-9526-39787a5bd7cb.png)

**Comment by WorldSkillsFrance** [comment] 2018-05-15 10:25
Here @PierreAnctil  a video of multiple modification who this does not work : 
https://www.dropbox.com/s/szlimnu1zp9jfqn/Bug%20request%20modification.trec?dl=0

**Comment by PierreAnctil** [comment] 2018-05-15 14:04
@WorldSkillsFrance OK thanks, that will help

**Comment by PierreAnctil** [comment] 2018-05-23 09:58
@Simon-Woirgard  @ailtisWSFR 

I tried to reproduce the bug with production data and I still can't (video below might need time to load):

![2018-05-23_11-55-10](https://user-images.githubusercontent.com/6544411/40417515-374b634c-5e80-11e8-8e66-bff1e5ed750f.gif)

Do you still encounter this issue?

**Comment by ailtisWSFR** [comment] 2018-05-29 09:08
@PierreAnctil Yes, we still encounter this issue. Just try today with production data and still the same problem, see video linked below : 

[https://www.dropbox.com/s/fau42cm4il591t5/Mass%20edit%20bug%201.mp4?dl=0](url)

Since we are actually working on the infrastructure list with the host of the event, it becomes urgent to solve this issue. 
Thanks in advance.

**Comment by PierreAnctil** [comment] 2018-05-29 10:40
@ailtisWSFR can you tell me what your permissions are on https://people.worldskills.org/#/people/person/28347/permissions ?

**Comment by ailtisWSFR** [comment] 2018-05-29 11:11
@PierreAnctil My Position and Permissions : 
Position : IL Manager (2018)
Permissions : FR - Admin

And the screenshot of my "Individual permissions for all applications" regarding IL : 
![image](https://user-images.githubusercontent.com/39295271/40655471-bbbc38b6-6341-11e8-8827-7ae87ba5eb3d.png)

**Comment by PierreAnctil** [comment] 2018-05-29 15:00
@ailtisWSFR 
I still cannot reproduce it.
I do not have sufficient permission to test it in production.

Do you have it right after landing on the page? Or do you do something in the page before? Does it always happen? With the same data ?

**Comment by PierreAnctil** [comment] 2018-05-29 15:05
@ailtisWSFR or maybe you can add me the EditItemStatus permission so I can test it? Or @fabian can do it?

**Comment by ailtisWSFR** [comment] 2018-05-29 15:37
@PierreAnctil As shown in the video, I don't do anything more on the page then what is shown in the video. 
This problem seems to appear when you have different status applied to the lines that you want to update, but I haven't tried other configuration.
If @fabian is OK and if it helps, I'm OK too to give you the permission. (but in your video posted 6 days ago with TARKETT, you seemed to already have the correct permission to make the action that I do in my video...)

**Comment by ailtisWSFR** [comment] 2018-05-29 15:43
@PierreAnctil This is what appears on the "Console" : 
![image](https://user-images.githubusercontent.com/39295271/40669671-c4452508-6367-11e8-8029-fecfc821411b.png)

**Comment by fabian** [comment] 2018-05-30 08:14
@ailtisWSFR I just tried to reproduce the problem on the production environment with your account (I can simulate your user) and didn't get any errors.

@PierreAnctil Could it be that the items didn't have a category yet but have them now?

**Comment by PierreAnctil** [comment] 2018-05-30 08:22
@fabian I already checked that and all items have a category on the FR event.

@fabian @ailtisWSFR we reproduced the issue on @lorentzClaude computer. The modal was closing too early and its scope was lost (still cannot figure out why this was working on my end and in staging and in production when @fabian tested though).

We have a fix ready, the PR will come soon.

**Comment by ailtisWSFR** [comment] 2018-06-01 09:02
@fabian @PierreAnctil I'm sorry to let you know that I just tried now and still have the exact same bug...
Is there some kind of time that I need to wait for the fix to be effective in the IL (production)?

**Comment by fabian** [comment] 2018-06-01 09:09
@ailtisWSFR Sorry, this fix hasn't been pushed to production yet, will do that on Monday. Got closed automatically by the commit comment.

**Comment by ailtisWSFR** [comment] 2018-06-01 09:14
Ok, no problem, thank for that.

**Comment by ailtisWSFR** [comment] 2018-06-05 08:38
Juste tested the tool now and it does work properly! Thank you very much all! 👍

**Closed** 2018-06-05 08:41 UTC
Labels: bug
